import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/devil-breeze"
          rel="stylesheet"
        />
        <link href="https://fonts.cdnfonts.com/css/poppins" rel="stylesheet" />
        <link href="https://fonts.cdnfonts.com/css/bimbo" rel="stylesheet" />
      </head>
      <body className="antialiased">
        <Header />
        <div className="page-content">{children}</div>
      </body>
    </html>
  );
}
